# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
url: "http://wahibhaq.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
#title: Wahib Ul Haq

# Short description of your site
description: A Personal Website and Blog !

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-face.jpeg"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Projects: "projects"
  Resume: "resume-simple.html"
  About Me: "aboutme"


# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Wahib Ul Haq
  email: "wahib.tech@gmail.com"
#  facebook: yourname  # eg. daattali
  github: wahibhaq    # eg. daattali
  twitter: wahibhaq   # eg. daattali
  linkedin: "in/wahibhaq"  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: "1016544/wahib-haq"  # eg. "3943160/daattali"
  # quora: "profile/Wahib-Ul-Haq"

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: true
  stackoverflow: true
  # quora: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "wahibhaq.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: "wahibulhaq"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-72521032-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge #pygments
permalink: /blog/:title/
paginate: 5
paginate_path: "/page:num/"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true


# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
